## config

## spring config
spring:
  profiles:
    active: dev
  application:
    name: stock-alert
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver

## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.ljq.stock.alert.model.entity

## log
logging:
  level:
    com.ljq.stock.alert.dao: debug

## 异常日志栈深度
exceptionLogStackDepth: 5


